### ISSUE TITLE
ES6 bundle being used in node?

### ISSUE THREAD

**Issue by JuanCaicedo** [tsouza/yajs#1]
Hi there! I'm playing around with yajs and had a problem loading it in node. The main function doesn't seem to be available here
```js
const yajs = require('yajson-stream')
yajs('$') // TypeError: yajs is not a function
```
I think this might be because the bundle being used by node is bundled for use by ES6 imports
```js
const yajs = require('yajson-stream').default
yajs('$') // works fine
```

I put together [this glitch](https://glitch.com/edit/#!/plume-lamp?path=server.js:7:0) to show what I'm seeing

A solution I thought of while reading [this article](https://hashnode.com/post/write-clean-npm-packages-and-make-them-esm-ready-cj6m68sc701esnfwu5gzrp0az) would be to set `"main"` in `package.json` to point to a node bundle and `"module"` to point to an ES6 module. 

Alternately, the documentation could just be updated to use `require('yajson-stream').default`. 

Let me know if you want any help with this 😀

**Comment by tsouza** [comment]
You are completely right. I will fix this.

Or you can just send a PR if you want :)

**Comment by tsouza** [comment]
Fixed by https://github.com/tsouza/yajs/commit/aac867df83fcd42f6a902da0e8f2ff8e89807508
