### ISSUE TITLE
Multiple key filters

### ISSUE THREAD

**Issue by JuanCaicedo** [tsouza/yajs#2]
Feel free to close this if it's no a feature you want to support, no hard feelings 😀

Right now I don't think it's possible to apply multiple key filters. I put together [this example](https://glitch.com/edit/#!/plume-lamp?path=server.js:22:92) in which I try to apply two filters, but only the first gets applied.

```js
yajs('$.array{x}{special}') // does not throw error, but only applies {} 
```

The API that oboe supports is like this. I think that shorthand makes a lot of sense
```js
oboe(source)
  .node('$.array.{x, special}')
```

Let me know if I can provide more info or you want help implementing this!

**Comment by tsouza** [comment]
It is possible. Documentation sucks at this point, sorry. The filter is actually a boolean expression, so you can do like:
```js
yajs('$.array{x && special}')
```

If all you want to do is only an 'OR' expression, then this is faster:
```js
yajs('$.array{x special}')
```
Which is equivalent to:
```js
yajs('$.array{x || special}')
```

**Comment by tsouza** [comment]
I will close this for now, please reopen if you have further issues on this.
